
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('experiences').del()
    .then(function () {
      // Inserts seed entries
      return knex('experiences').insert([
        {title: 'Dog Walking', rating: 4, user_id: 1, org_id: 1, description: 'I walked dogs for the Humane Society of Boulder valley', role: 'general', hours: 1, minutes:15},
        {title: 'Sock-Hop', rating: 4, user_id: 1, org_id: 4, description: 'set-up and tear down of social sock hop event', role: 'general', hours: 3, minutes:0},
      ]);
    });
};


[

  {
    "First name": "Doris",
    "Last name": "Vermillion",
    "Organization name": "Pangea Organics",
    "Date": "04/22/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "tree planting",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Doris",
    "Last name": "Vermillion",
    "Organization name": "Lyons County Arts Alliance",
    "Date": "04/05/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Lyons Arts Week - completed surveys",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "12/21/2016",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Mentorship from BJ on how to collaborate with a dev team and leadership to form meaningful relationships and requirements, with product/market validated fit. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Irma",
    "Last name": "Patterson",
    "Organization name": "San Francisco Police Department - Victim Advocate Program",
    "Date": "04/28/2017",
    "Hours": 60,
    "Minutes": 0,
    "Description": "Received 3 pages from dispatch this weekend. 2 hospital on scene calls and 1 phone call follow up was made",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Irma",
    "Last name": "Patterson",
    "Organization name": "San Francisco Police Department - Victim Advocate Program",
    "Date": "03/09/2017",
    "Hours": 60,
    "Minutes": 0,
    "Description": "On call all weekend for victims if they need assistance. Received two calls this weekend",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Girls on the Run",
    "Date": "10/08/2016",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Moonball!!!",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "03/02/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Made and served grilled cheese, cleaned and entertained as well as helped with breakdown.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "05/17/2017",
    "Hours": 2,
    "Minutes": 48,
    "Description": "Tutoring kids after school",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "10/02/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "work for gamma phi over the week",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Aaron",
    "Last name": "Schaef",
    "Organization name": "Community Food Share",
    "Date": "05/10/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Sorted and packed over 3100 pounds of frozen meat and ready-to-eat frozen meals with a small team of 4 other volunteers.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/16/2015",
    "Hours": 6,
    "Minutes": 30,
    "Description": "tore down and rebuilt houses in Nepal",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/17/2015",
    "Hours": 6,
    "Minutes": 30,
    "Description": "tore down and rebuilt houses in Nepal",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "08/16/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Held two 1-1 interviews with Seth Chaps and Kay Hutchison. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "12/20/2016",
    "Hours": 3,
    "Minutes": 30,
    "Description": "Mentorship from BJ on how to create a release plan and narrow down to an MVP. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "05/16/2017",
    "Hours": 2,
    "Minutes": 18,
    "Description": "Tutoring kids after school",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/13/2016",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Decoration crew. Decorate stage, grounds, greenrooms, dining area, backstage, ticket office and town.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/14/2016",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Decoration crew. Decorate stage, grounds, greenrooms, dining area, backstage, ticket office and town.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/15/2016",
    "Hours": 10,
    "Minutes": 0,
    "Description": "Decoration crew. Decorate stage, grounds, greenrooms, dining area, backstage, ticket office and town.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/20/2016",
    "Hours": 5,
    "Minutes": 0,
    "Description": "Decoration crew. Breakdown day. Tear down decorations on stage, grounds, greenrooms, dining area, backstage, ticket office and town.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/12/2015",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Went to Nepal after the earthquakes to help rebuild a village",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/13/2015",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Helped tear down and rebuild homes in Nepal",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/14/2015",
    "Hours": 6,
    "Minutes": 0,
    "Description": "Tore down and rebuilt homes in Nepal",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Himalayan Development Foundation",
    "Date": "11/15/2015",
    "Hours": 5,
    "Minutes": 0,
    "Description": "tore down and rebuilt houses in Nepal",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/10/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/11/2017",
    "Hours": 6,
    "Minutes": 48,
    "Description": "artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/12/2017",
    "Hours": 9,
    "Minutes": 30,
    "Description": "artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/14/2017",
    "Hours": 8,
    "Minutes": 30,
    "Description": "Box office",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/14/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Marissa",
    "Last name": "MacDonald",
    "Organization name": "First Presbyterian Church of Lyons",
    "Date": "06/04/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Sunday school classroom leader",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Doris",
    "Last name": "Vermillion",
    "Organization name": "LMA - Lyons Mountainbike Alliance",
    "Date": "02/04/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Committee Retreat",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "08/10/2017",
    "Hours": 1,
    "Minutes": 0,
    "Description": "Attended Posture in the Workplace lunch workshow run by Lyons Pilates with Madeline. Learned different stances and rolling shoulder exercises to realign your core. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "12/06/2016",
    "Hours": 2,
    "Minutes": 30,
    "Description": "Mentored by BJ on how to divide up a mock into stories, write them, and acceptance test them. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Doris",
    "Last name": "Vermillion",
    "Organization name": "Community Food Share",
    "Date": "05/10/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Sorted non perishable food",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Doris",
    "Last name": "Vermillion",
    "Organization name": "Community Cycles",
    "Date": "06/13/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Worked on open street maps for People For Bikes networking intiative.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/14/2017",
    "Hours": 2,
    "Minutes": 30,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/15/2017",
    "Hours": 9,
    "Minutes": 18,
    "Description": "Box office",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/15/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Box office",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/16/2017",
    "Hours": 7,
    "Minutes": 30,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/17/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/18/2017",
    "Hours": 11,
    "Minutes": 0,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/19/2017",
    "Hours": 14,
    "Minutes": 0,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/19/2017",
    "Hours": 0,
    "Minutes": 30,
    "Description": "Artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "06/19/2017",
    "Hours": 8,
    "Minutes": 30,
    "Description": "Breakdown day/artist hospitality",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Mary",
    "Last name": "Cruise",
    "Organization name": "A Precious Child",
    "Date": "06/06/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Client Services and Inspiring Minds Center",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Mary",
    "Last name": "Cruise",
    "Organization name": "A Precious Child",
    "Date": "06/07/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Client Services and Inspiring Minds Center",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Irma",
    "Last name": "Patterson",
    "Organization name": "San Francisco Police Department - Victim Advocate Program",
    "Date": "06/16/2017",
    "Hours": 60,
    "Minutes": 0,
    "Description": "Received zero phone calls this weekend :) :(",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "07/27/2017",
    "Hours": 0,
    "Minutes": 30,
    "Description": "Will helped me set up iOS and Android simulators on my machine and taught me how to use them to run through mobile acceptance tests. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "10/22/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Triple threat clean up with zbt",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Mary",
    "Last name": "Cruise",
    "Organization name": "A Precious Child",
    "Date": "06/05/2017",
    "Hours": 7,
    "Minutes": 0,
    "Description": "Client Services and Inspiring Minds Center",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Marissa",
    "Last name": "MacDonald",
    "Organization name": "First Presbyterian Church of Lyons",
    "Date": "08/30/2017",
    "Hours": 3,
    "Minutes": 18,
    "Description": "Get Involved\" CU fair",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Unself",
    "Date": "08/30/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Pitched Unself",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Marissa",
    "Last name": "MacDonald",
    "Organization name": "First Presbyterian Church of Lyons",
    "Date": "06/11/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Sunday school classroom leader",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Marissa",
    "Last name": "MacDonald",
    "Organization name": "First Presbyterian Church of Lyons",
    "Date": "06/25/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Sunday school classroom leader",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "04/19/2017",
    "Hours": 1,
    "Minutes": 0,
    "Description": "Attended overview of Tom Badd Operations roles and tasks run by Ali. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Gamma Phi Beta",
    "Date": "10/02/2017",
    "Hours": 3,
    "Minutes": 30,
    "Description": "Work for my position",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Amber",
    "Last name": "Maple",
    "Organization name": "YMCA of Lyons Valley",
    "Date": "11/07/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Basketball practice",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Bridge House",
    "Date": "11/27/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Prepped place settings and cleaned up the kitchen after serving food to ~70 people experiencing homelessness a hot dinner",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Sarah",
    "Last name": "Gray",
    "Organization name": "The GrowHaus",
    "Date": "07/07/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Worked weighing and organizing CSA style farm boxes for community surrounding The Growhaus. Sign up includes filling out a waiver but otherwise not extensive. Great experience learning and meeting new people.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Sarah",
    "Last name": "Gray",
    "Organization name": "Community Food Share",
    "Date": "07/28/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Worked on a farm operated by community food share harvesting vegetables for their donation program. Easy sign up, initiation and friendly leaders.",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Lyons volunteers",
    "Date": "07/19/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Helping rebuild houses after the flood",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "07/17/2017",
    "Hours": 3,
    "Minutes": 0,
    "Description": "Decoration crew- set up",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "07/18/2017",
    "Hours": 3,
    "Minutes": 30,
    "Description": "Decoration crew- set up",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Planet Bluegrass",
    "Date": "07/20/2017",
    "Hours": 4,
    "Minutes": 0,
    "Description": "Decoration crew- set up",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Mary",
    "Last name": "Cruise",
    "Organization name": "A Precious Child",
    "Date": "06/14/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Client Services and Inspiring Minds Center",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Mary",
    "Last name": "Cruise",
    "Organization name": "A Precious Child",
    "Date": "06/13/2017",
    "Hours": 8,
    "Minutes": 0,
    "Description": "Client Services and Inspiring Minds Center",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Alyssa",
    "Last name": "Havemann",
    "Organization name": "Community Food Share",
    "Date": "07/17/2017",
    "Hours": 1,
    "Minutes": 0,
    "Description": "Orientation",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  },
  {
    "First name": "Ayesha",
    "Last name": "Jilani",
    "Organization name": "Unself",
    "Date": "02/07/2017",
    "Hours": 2,
    "Minutes": 0,
    "Description": "Governance meeting presentation to leadership; practice public speaking. #professionaldevelopment",
    "Role": "General Volunteer",
    "How was the experience?": "",
    "How were you feeling before this experience?": "",
    "How were you feeling after this experience?": ""
  }
]
